{   'adj_mode': <AdjacencyMode.OneStep: 'OneStep'>,
    'batch_size': 256,
    'console_log_freq': 1,
    'dataset_name': <Dataset.OGBN_PRODUCTS: 'ogbn-products'>,
    'do_train_tqdm_logging': False,
    'dropout': 0.5,
    'force_cpu': False,
    'hidden_size': 128,
    'lr': 0.001,
    'model_type': <ModelType.GATV1: 'GAT-V1'>,
    'nbor_degree': 2,
    'num_heads': 1,
    'num_of_epochs': 500,
    'num_of_layers': 3,
    'num_of_runs': 1,
    'num_workers': 2,
    'patience_period': 100,
    'sparse': True,
    'test_batch_size': 256,
    'test_frequency': 1,
    'use_batch_norm': False,
    'use_layer_norm': False}

torch.cuda is available: True
Used Dataset: ogbn-products

Run 01:

Epoch 01| Loss: 1.2132| Acc: 0.7301| Train Time: 150.3798s
Printing only the traceback above the current stack frame
Traceback (most recent call last):
  File "c:\Users\doria\Desktop\ProseminarMA\multiscale-softattention\utils\experimentor_base.py", line 219, in run_wrapper
    self.run()
  File "c:\Users\doria\Desktop\ProseminarMA\multiscale-softattention\utils\experimentor_base.py", line 173, in run
    train_acc, val_acc, test_acc, eval_time = self.test()
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "c:\Users\doria\Desktop\ProseminarMA\multiscale-softattention\utils\experimentor_base.py", line 126, in test
    out = self.model.inference(self.x, loader = self.test_loader)
  File "c:\Users\doria\Desktop\ProseminarMA\multiscale-softattention\models\base\Net.py", line 80, in inference
    edge_index, edge_weight = self.one_step_gen(edge_index, self.nbor_degree, x.size(0), self.device)
  File "c:\Users\doria\Desktop\ProseminarMA\multiscale-softattention\utils\utils.py", line 36, in one_step_sparse
    adj_powers.append(torch.sparse.mm(k1, k0))
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\torch\sparse\__init__.py", line 90, in mm
    return torch._sparse_sparse_matmul(mat1, mat2)
RuntimeError: for_each: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered


Printing the full traceback as if we had not caught it here...
Traceback (most recent call last):
  File "C:\Users\doria\anaconda3\envs\PS\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\doria\anaconda3\envs\PS\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
    self.io_loop.start()
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\doria\anaconda3\envs\PS\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\doria\anaconda3\envs\PS\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Users\doria\anaconda3\envs\PS\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\ipykernel\kernelbase.py", line 457, in dispatch_queue
    await self.process_one()
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\ipykernel\kernelbase.py", line 446, in process_one
    await dispatch(*args)
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
    await result
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
    reply_content = await reply_content
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\ipykernel\ipkernel.py", line 345, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\ipykernel\zmqshell.py", line 532, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\IPython\core\interactiveshell.py", line 2898, in run_cell
    result = self._run_cell(
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\IPython\core\interactiveshell.py", line 2944, in _run_cell
    return runner(coro)
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\IPython\core\interactiveshell.py", line 3169, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\IPython\core\interactiveshell.py", line 3361, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\doria\AppData\Local\Temp/ipykernel_13656/2879061996.py", line 3, in <module>
    experimentor.run_wrapper()
  File "c:\Users\doria\Desktop\ProseminarMA\multiscale-softattention\utils\experimentor_base.py", line 219, in run_wrapper
    self.run()
  File "c:\Users\doria\Desktop\ProseminarMA\multiscale-softattention\utils\experimentor_base.py", line 173, in run
    train_acc, val_acc, test_acc, eval_time = self.test()
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "c:\Users\doria\Desktop\ProseminarMA\multiscale-softattention\utils\experimentor_base.py", line 126, in test
    out = self.model.inference(self.x, loader = self.test_loader)
  File "c:\Users\doria\Desktop\ProseminarMA\multiscale-softattention\models\base\Net.py", line 80, in inference
    edge_index, edge_weight = self.one_step_gen(edge_index, self.nbor_degree, x.size(0), self.device)
  File "c:\Users\doria\Desktop\ProseminarMA\multiscale-softattention\utils\utils.py", line 36, in one_step_sparse
    adj_powers.append(torch.sparse.mm(k1, k0))
  File "C:\Users\doria\anaconda3\envs\PS\lib\site-packages\torch\sparse\__init__.py", line 90, in mm
    return torch._sparse_sparse_matmul(mat1, mat2)
RuntimeError: for_each: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
